---
layout: post
title: "8장 예외처리"
date: 2025-04-11 09:47:23
---

## 8장 예외처리

**요약:** 객체지향 공부

# 프로그램 오류
## 종류
  1. 컴파일에러(compile-time error)
  1. 런타임 에러(runtime error)
  1. 논리적 에러(logical error)
## 컴파일 에러 → 컴파일할떄 발생하는 에러

```java
public class ch8_1 {
    public static void main(String[] args) {
        system.out.println("dasdsad");//컴파일 에러 -> 아이들에서 자동으로 체크해줌
    }
}
```

## 런타임 에러 → 실행중 발생하는 에러

```java
public class ch8_1 {
    public static void main(String[] args) {
        System.out.println(args[0]);
    }
}
```


```shell
/Users/gimgyeongmin/Library/Java/JavaVirtualMachines/corretto-21.0.6/Contents/Home/bin/java -javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=59844 -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath /Users/gimgyeongmin/java_study/out/production/java_study ch.ch8_1
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at ch.ch8_1.main(ch8_1.java:5)

Process finished with exit code 1
```

### java의 런타임 에러 종류
  - 에러(error)→ 프로그램 코드에 의해서 수습될 수 없는 심각한 오류
  - 예외(exception) → 프로그램 코드에 의해서 수습될 수 있는 다소 미약한 오류
### 예외처리의 정의와 목적
  - 정의 → 프로그램 실행 시 발생할 수 있는 예외의 발생에 대비한 코드를 작성하는 것
  - 목적 → 프로그램의 비정상 종료를 막고 정상적인 실행상태를 유지하는것
  - Exception 클래스들 → 사용자 실수(외부요인)
  - RuntimeException → 프로그래머의 실수로 발생하는 예외   
## 논리적 에러 → 작성의도와 다르게 동작
## 예외 처리하기 Try-catch문

```java
package ch;

public class ch8_1 {
    public static void main(String[] args) {
        try {
            System.out.println(args[0]);
        }
        catch (Exception1 e1){
            //Exception1에러가 발생했을때 처리하는문장
        }
        catch (Exception2 e1){
            //Exception2에러가 발생했을때 처리하는문장
        }
        catch (Exception e){
            //이외의 나머지에러 발생했을때 처리하는문장
        }
    }
}
```

## printStackTrace()and getMessage()
  - printStackTrace() → 예외발생 당시의 호출 스택에있던 메서드 정보와 예외 메시지를 화면에 출력한다.
  - getMessage() = String → 발상한 예외클래스의 인스턴스에 저장된 메시지를 얻을 수 있다.

```java
package ch;

public class ch8_1 {
    public static void main(String[] args) {
        try {
//            System.out.println(args[0]);
            System.out.println(4/0);
        }
        catch (IndexOutOfBoundsException e){
            System.out.println("헤이 말이안되잖아");
            //Exception1에러가 발생했을때 처리하는문장
        }
        catch (ArithmeticException ae ){
            ae.printStackTrace();
            System.out.println( );
            System.out.println("예외 메세지 : " +  ae.getMessage());
            //Exception2에러가 발생했을때 처리하는문장
        }
        catch (Exception e){
            System.out.println("어이가없네");
            //이외의 나머지에러 발생했을때 처리하는문장
        }
    }
}
```

## 멀티 catch 블럭
  - 내용이 같은 catch블럭을 하나로 합친것
  - 내용이 같은 catch블럭

```java
package ch;

public class ch8_1 {
    public static void main(String[] args) {
        try {
//            System.out.println(args[0]);
            System.out.println(4/0);
        }
        catch (ArithmeticException | IndexOutOfBoundsException ae){
            ae.printStackTrace();
            System.out.println( );
            System.out.println("예외 메세지 : " +  ae.getMessage());
            //Exception2에러가 발생했을때 처리하는문장
        }
        catch (Exception e){
            System.out.println("어이가없네");
            //이외의 나머지에러 발생했을때 처리하는문장
        }
    }
}
```

## 예외 발생시키기
  1. 연산자 new를 이용해서 발생시키려는 예외 클래스의 객체를 만든 다음
  1. 키워드 throw를 이용해서 예외를 발생시킨다.

```java
package ch;

public class ch08_1 {
    public static void main(String[] args) {
        try{
            Exception e = new Exception();//객체를 생성해서
            System.out.println(e);
            throw e;//throw를 사용해서 던짐
        }
        catch(Exception e){
            e.printStackTrace();
            System.out.printf("공부하기싫다 오류 만들어 버렷");
        }
    }
}
```

## Checked예외, unchecked예외
  - Checked예외 → 컴파일러가 예외 처리 여부를 체크(필수)
  - unckecked예외 → 컴파일러가 예외 처리 여부를 체크 안함(선택)
### checked예외

```java
package ch;

public class ch08_1 {
    public static void main(String[] args) {
        throw new Exception();//오류 발생 필수로 체크해야함 컴파일 오류 발생!!
    }
}
```

### unchecked 예외

```java
package ch;

public class ch08_1 {
    public static void main(String[] args) {
        throw new RuntimeException();//컴파일 오류 안남!! 런타임오류발생!!
    }
    
}
```

## 메서드에 예외 선언하기
- 방법
  1. try-catch문
  1. 예외 선언하기(예외 떠넘기기)
  1. 은폐
- 메서드가 호출시 발생가능한 예외를 호출하는 쪽에 알리는것

```java
package ch;

public class ch08_1 {
    public static void main(String[] args) {
        throw new RuntimeException();
    }
    void method() throws ArrayIndexOutOfBoundsException,Exception,RuntimeException {//메서드의 예외를 선언
        //~~~
    }
    void method2 ()throws Exception{//모든예외 발생가능
        if(!enoughSpace()){
            throw new SpaceException("공간 부족 ");//오류 던지기 
        }
        throw new MemoryException("메모리 부족!!");
    }
}}
```

### finally블럭

```java
package ch;

public class ch08_1 {
    public static void main(String[] args) {
        try {
            throw new RuntimeException();
        }
        catch (RuntimeException e){
            System.out.println("근하하하");
        }
        finally {
            System.out.printf("마지막 막막");//오류가 나던말단 마지막에 수행됨
        }
    }

}
```

## 사용자 정의 예외 만들기
  - 우리가 직접 예외 클래스를 정의할 수 있음
  - 조상은 Exception과 RuntimeException중 선택

```java
class CoustomException extends Exception{//필수 
    CoustomException(String msg){//defualt하게 String문자열을 매개변수로 받는 생성자
        super(msg);//조상인 Exception호출
    }
}
```

### 예외 되던지기
  - 예외를 처리한 후에 다시 예외를 발생시키는 것
  - 호출한 메서드와 호출된 메서드 양쪽 모두에서 예외처리하는것

```java
class d2312{
    public static void main(String[] args) {
        try {
            method1();
        }
        catch (Exception e){
            System.out.println("2번처리");//2번 예외처리
        }
    }
    static void method1() throws Exception{
        try {
            throw new Exception();
        }
        catch (Exception e){
            System.out.println("1번처리");//1번 예외처리
            throw e;//던지기
        }

    }
}
```

## 연결된 예외(chained exception)
  - 한 예외가 다른 예외를 발생시킬 수 있다.
  - 예외 A가 예외 B를 발생 시키면 A는 B의 원인 예외(cause excepiton) 
  - 예외를 묶을 때 사용
  - checked 예외를 unchecked예외로 변경할떄 사용

```java
class a1323{
    public static void main(String[] args) {
        try {
            a();
        }catch ( aException e){
            bException b = new bException("연결된예외")n;
            b.add(a);
            thorw b;
        }
    }
}
```

checked 예외를 unchecked예외로 변경할떄 사용

```java
    static void startInstall() throws SpaceException, MemoryException{
        if(!enoughSpace())
            throw new SpaceException("1"); 
        if(!enoughMemory())
            throw new MemoryException("2");//checked
    }
    
    static void startInstall1() throws SpaceException{
        if(!enoughSpace())
            throw new SpaceException("1");
        if(!enoughMemory())
            throw new RuntimeException( new MemoryException("2"));//checked -> unckecked로 변환
    } 
```
